version: "3.8"

services:
  server:
    build: ./server
    container_name: server
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - ./server/.env
    volumes:
      - ./server:/app
      - /app/node_modules
    command: npm run dev

  client:
    build: ./client
    container_name: client
    ports:
      - "5173:5173"
    volumes:
      - ./client:/app
      - /app/node_modules
    depends_on:
      - server
    command: npm run dev